name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '46 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://opendata.arcgis.com/datasets/7776d2ae87eb4dddbc5aca0a73fb01ae_61.geojson | jq . > opendata/us/oregon/portland/ada_ramps.geojson
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest curb ramps: ${timestamp}" || exit 0
        git push



